### PR TITLE
Implement Solidity Style Guide

### PR DESCRIPTION
**Pull request by PJUllrich**
**DON'T MERGE (YET)**
Hi there, 

I started to implement the official Solidity Style Guide and began with adding indentation within Struct and Event blocks. This was only a test to see whether 1) I understand your code and 2) I'm sure how to make changes to it.

I don't know how I can test these changes yet, so I would appreciate it if you could give me a hint how to do that. Once I can test my changes, I will begin with implementing the full style guide. 
Especially: How can I run the code formatter on an example contract? I'd then check with another tool (solium) whether the code style is correct or not. 

Greetings from the freezing Netherlands!

### CODE REVIEW

**Comment by SerCeMan** [comment]
Hi, @PJUllrich!

Thank you for the contribution! 

> I don't know how I can test these changes yet, so I would appreciate it if you could give me a hint how to do that.

In order to test formatting changes, you can take a look at `me.serce.solidity.ide.formatting.SolidityFormattingTest`. It uses test files located in `src/test/resources/fixtures/formatter`. Every test uses its name to find two files, e.g. `testAssembly` uses two files: `assembly.sol` and `assembly-after.sol`. The test runs formatting on `assembly.sol` and compares the result to expected result in `assembly-after.sol`. 

You definitely made changes in the right place, but I'm not sure what you tried to achieve, so it's better to add a test which can validate correctness and make sure that no one will break the change at some point.

P.S. Yeah, I know what freezing is, that's why I'm currently based in Sydney :)

**Comment by SerCeMan** [comment]
@PJUllrich You need to update the plugin to 2.0.3 version (plugins.jetbrains.com/plugin/9475-intellij-solidity). There is a chance that you need to do it manually (by opening setting -> plugins and clicking update there)

**Comment by PJUllrich** [comment]
Oooooooohhhhhh....

Well that's definitely easier than forking, contributing, building, testing, and despairing 😆 

That fixed it. Thank you. The WebStorm Plugin store didn't show that there was an update available. I had to go to "Browse Repositories" and there I could see it. This seems rather like a WebStorm bug .

Well anyhow, thanks again! 😄

**Comment by SerCeMan** [comment]
Although, I guess that formatting still doesn't do what it is expected to do. E.g., the resulted code for the function call:
```
  function test() {
    choices.push(Choice({
      name : question,
      count : 0
      }));
  }
```

**Comment by PJUllrich** [comment]
Yes, that's correct. The `}));` should have one indent less.

**Pull request closed without merging**
