### PR TITLE
Inspection to catch possible errors when function doesn't return a result

### PR DESCRIPTION
**Pull request by 0v1se**
An inspection to catch something like this:

    function transfer(address _to, uint _value) public returns (bool) {
        onTransfer(msg.sender);
        /*return needed*/ super.transfer(_to, _value);
    }

also, catches the same situation when there is no assignment to return variable

### CODE REVIEW

**Comment by 0v1se** [comment]
Sure, will check these examples

**Comment by 0v1se** [comment]
@SerCeMan 
**p.1** fixed, but some other tests failed. I think, there was a bug in solidity.bnf. Pls, review this. (assignment expression should be higher than any other expression)
Pls. see https://github.com/JetBrains/Grammar-Kit/blob/master/HOWTO.md

**p.2** - didn't implement this for assemly blocks. will try to add this too

**p.3** - I think it's not possible to say precisely if result variable can or can not be assigned. In this situation user should suppress this inspection (so he reviewed the code and he's sure about safety of it)

**Comment by 0v1se** [comment]
@SerCeMan let me know when you consider about **p.1**. Is the bug correctly fixed? (I think, plugin was not building tree correctly - SolAssignmentExpression should be root in the tree)

**Comment by 0v1se** [comment]
Also, implemented this inspection for assembly blocks (basic support. will think more about this)

Had to remove private modifier for `IdentifierOrList` in solidity.bnf (because didn't have information about var name)

**Comment by 0v1se** [comment]
@SerCeMan I added private modifier to helper extensions.

Also, I fixed tests.
But I am not sure about ternary expression. Pls look at https://github.com/daonomic/intellij-solidity/blob/d6ce2b75fa0801d540fabce2b8dda720ebda4692/src/test/resources/fixtures/parser/ternary.txt#L21

Clearly, SolAssignmentExpressionImpl should be the root here.

**Comment by SerCeMan** [comment]
> Clearly, SolAssignmentExpressionImpl should be the root here.

I agree regarding this example, but we also need to consider the following example taken from 
`src/test/resources/fixtures/parser/solidity_official_tests/shouldSucceed/conditionalWithAssignment.sol` which has started failing (https://github.com/intellij-solidity/intellij-solidity/pull/111/files#diff-3adbc3e9da612bd5d08c08de0c43f955R92)

```solidity
contract A {
  function f() {
    uint y = 1;
    uint x = 3 < 0 ? x = 3 : 6;
    true ? x = 3 : 4;
  }
}
```

After digging a bit, I realised that this ambiguity can be fixed by rewriting in the following way:
```patch
Index: src/main/grammars/solidity.bnf
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/main/grammars/solidity.bnf	(date 1538372349000)
+++ src/main/grammars/solidity.bnf	(date 1538374630000)
@@ -337,7 +337,8 @@
 
 AssignmentExpression ::= Expression ('=' | '|=' | '^=' | '&=' | '<<=' | '>>=' | '+=' | '-=' | '*=' | '/=' | '%=') Expression { rightAssociative=true }
 InlineArrayExpression ::= '[' Expression (',' Expression)* ']'
-TernaryExpression ::= Expression '?' Expression ':' Expression
+TernaryExpression ::= Expression '?' RightTernaryExpression
+private RightTernaryExpression ::= Expression ':' Expression
 OrExpression ::= Expression '||' Expression
 AndExpression ::= Expression '&&' Expression
 EqExpression ::= Expression ('==' | '!=') Expression
```

This change should fix the failing test.

**Pull request merged**
