### PR TITLE
import handling improvements

### PR DESCRIPTION
**Pull request by mbolotov**
1. validate import paths and names
2. autocomplete import paths
3. auto import action for names in a qualified function call expression (e.g. MyContract.myFunction())

### CODE REVIEW

**Review by SerCeMan — APPROVED** [review]
Thanks 👍

**Comment by SerCeMan** [comment]
Hey, @mbolotov! Could you resolve the conflicts that seemed to have arisen from other PRs? I could do this as well, but it'll affect the ownership, and if you do it, it'll be fully preserved. 👍

**Comment by mbolotov** [comment]
Done

**Comment by mbolotov** [comment]
CI build showed `testFunctionTypeInExpression` failed. However, I'm unable to reproduce this failure at my side. 
@SerCeMan what do you think? Should we just try to restart the build?

**Pull request merged**
