### PR TITLE
Update grammar to include immutable keyword

### LINKED ISSUE #203: Errors when using immutable keyword
When using the `immutable` keyword the plugin reports some errors. The solidity code is a valid code and compiles correctly. If I remove the `immutable` keywords the errors disappears and the contract still compiles correctly. I'm facing this issue also with the latest v2.3.0 version

Here is an example code to reproduce this:
```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.6.10;

contract Greeter {
    uint256 internal immutable testVar;

    constructor() public {
        testVar = 1;
    }
}
```

Screenshots with errors
code
errors

### PR DESCRIPTION
**Pull request by patitonar**
Closes #203 

Please take a look if all required changes were implemented

### CODE REVIEW

**Comment by patitonar** [comment]
Updated the unit tests, looks like the CI is Ok now

**Review by SerCeMan — APPROVED** [review]
Awesome 🚀

**Comment by patitonar** [comment]
@SerCeMan Is there any plans to make a new release including the changes from this PR?

**Comment by SerCeMan** [comment]
Hy, @patitonar! It should be out as [2.3.1](https://github.com/intellij-solidity/intellij-solidity/releases/tag/2.3.1) at the beginning of the next week.

**Pull request merged**
