### PR TITLE
Event names completion after emit keyword

### PR DESCRIPTION
**Pull request by indegro**

### CODE REVIEW

**Comment by indegro** [comment]
@SerCeMan Thank you for review. Sure, will add tests

**Comment by indegro** [comment]
Hello, @SerCeMan 
I've added couple of test. Locally it passed. But I could not find the reason on travis. 
How can I extract test reports from travis?

Thanks in advance

**Comment by SerCeMan** [comment]
Hey, @indegro! It looks like the CI is 🍏! Do you still need a help with the tests?

**Comment by indegro** [comment]
Hello. I found that problem was only on windows platform. When I used linux box I managed to find the problem and solution :)

**Pull request merged**
