### PR TITLE
var resolve for

### PR DESCRIPTION
**Pull request by 0v1se**
* constructor args
* return variables

fix for https://github.com/intellij-solidity/intellij-solidity/issues/122
and for https://github.com/intellij-solidity/intellij-solidity/issues/115

### CODE REVIEW

**Comment by 0v1se** [comment]
@indegro it seems there is a problem with me.serce.solidity.lang.completion.SolEventCompletionTest.testEventExactCompletion

Sometimes it fails, sometimes it passes.

**Comment by indegro** [comment]
@0v1se Is it possible to provide test report?

**Comment by 0v1se** [comment]
@indegro the same test fails on my machine too
Also, I noticed: if I run all tests, this test passes.
If I run only this test - it fails 

What information do you need?
stacktrace: https://gist.github.com/0v1se/f2a97869bf034de06c36da552e1efe80

**Comment by indegro** [comment]
@0v1se I use linux desktop. Tried to run one test and in a bunch. It passed.
What is your configuration?

**Comment by 0v1se** [comment]
Everything's working as expected (in SolCompleter) - completion variants are provided correctly
It seems there is a problem in Intellij code.

**Comment by 0v1se** [comment]
@indegro I found out what happens.
If character 'C' is entered, then only one completion variant is provided, then Idea doesn't suggest anything. It silently completes with `ChildEvent`. If it completes silenty, then Lookup is disposed and LookupElements can not be found by fixture. (That's why this test sometimes fails, sometimes - not. Lookup disposing happens in other thread, so sometimes it happens after, sometimes - before)

The easiest way to fix the test is to add one more event with 'C'.
Will do

**Comment by 0v1se** [comment]
will reopen after test fix

**Comment by indegro** [comment]
@0v1se  Thank you!

**Pull request closed without merging**
