### PR TITLE
feat: add emit event parameters check

### PR DESCRIPTION
**Pull request by jonahcui**
Hi, team. I added an inspection to check event paraments. Please review it. If you have any confusion, please comment on it.

I have fixed the inheritance problem described in #350. The solidity doc is below:
[inheritance](https://docs.soliditylang.org/en/latest/contracts.html#multi-inheritance)

### CODE REVIEW

**Review by SerCeMan — COMMENTED** [review]
Hi, @jonahcui! Thank you for the PR, and sorry for the delay in reviewing it. 

I just checked out the branch, and it seems that it has broken a number of tests.

**Comment by SerCeMan** [comment]
All new inspections would also need a test, there are a few example of inspection tests in `me.serce.solidity.ide.inspections`, that way we'll be able to ensure that the change won't be broken in the future.

**Comment by jonahcui** [comment]
Ok, I will add a test quickly.

**Review by SerCeMan — APPROVED** [review]
Thank you! 👍

**Pull request merged**
