### PR TITLE
gas estimation display hints

### PR DESCRIPTION
**Pull request by mbolotov**
Limitations: 
1. supports `hardhat` framework only 
2. solc provides estimations for [some simple functions only](https://ethereum.stackexchange.com/questions/29725/infinite-gas-estimation-from-solc-for-simple-function)

### CODE REVIEW

**Comment by SerCeMan** [comment]
👋 Sorry for the delay, I'll have a look over the weekend.

**Comment by SerCeMan** [comment]
Hey, @mbolotov! Could you clarify how I could configure the project to test the new gas estimate functionality? I tried to test it with https://github.com/NomicFoundation/hardhat-boilerplate, but even after adding `hardhat-gas-reporter` explicitly, it's missing the `gasEstimates` in the resulting json. 

image

**Comment by mbolotov** [comment]
Hi @SerCeMan!
I'm sorry, I forgot to mention this.
Solc does not generate gas estimations by default. You may add the following element into the hardhad config to force it to do:

`solidity.compilers.settings`:           
```
          outputSelection: {
            '*': {
              '*': [
                "evm.gasEstimates",
              ] 
            },
          },
```

**Review by SerCeMan — APPROVED** [review]
That did it, thanks. 👍 

It might also be worth adding a few lines on how to enable it in the description of the inspection.

**Comment by mbolotov** [comment]
> It might also be worth adding a few lines on how to enable it in the description of the inspection.

it worth adding indeed. But I don't know where to add this description to. 
This is not an inspection. This is a hint provider + action. Do you know how they can be documented?

**Comment by SerCeMan** [comment]
Since the set-up might not very trivial, it might be worth describing the setup on Wiki, and linking the page from the action's description, https://github.com/intellij-solidity/intellij-solidity/wiki/. What do you think?

**Comment by shirotech** [comment]
I'm using hardhat and checked is showing, but I can't see the inlay. How to get it to show? Thanks.

**Comment by mbolotov** [comment]
and the most oblivious - did you enable the `Show Gas Estimation` action?

**Pull request merged**
