### PR TITLE
slight improvements to spacing rules (remove excess spacing)

### PR DESCRIPTION
**Pull request by moodysalem**
i tried to fix more of the problems people had with the rules but i'm not familiar enough with the interfaces. if you can guide me on the other problems that'd be great

also not sure why one test is failing when i used `./gradlew runIdea` to get the new -after files

### CODE REVIEW

**Comment by moodysalem** [comment]
the other rule I wanted to fix that really bothers me is the line break after else, not sure where that's represented in the spacing rules

and the other problem i wanted to fix is that when you start a new child of a struct, the indent is incorrect, it needs to be another level deeper

```
if (x < 3) {
    x += 1;
}
else {
    x -= 1;
}
```

**Comment by SerCeMan** [comment]
Hi, @moodysalem! Thanks for the contribution!

The change looks good to me apart from the failing test. 👍 

The `MultisigWallet` test probably fails because of the `com.intellij.psi.codeStyle.CommonCodeStyleSettings#KEEP_BLANK_LINES_IN_DECLARATIONS` setting. It's not exposed in solidity and therefore it's 2 by default. This behaviour seems ok to me given that you can change it to one line manually. But feel free to expose that setting in the solidity code style settings by adding `addBlankLinesTab(settings)` in the `me.serce.solidity.ide.formatting.SolCodeStyleSettingsProvider.SolCodeStyleMainPanel#initTabs`.

> it needs to be another level deeper

You can try to fix that with something like 

```
.betweenInside(STATEMENT, ELSE, IF_STATEMENT).spaces(1)
```

But you need to place that before the `.after(STATEMENT).lineBreakInCode()` because the order matters. 

But please open a separate PR if you want to fix the `if...else` issue :)

**Comment by SerCeMan** [comment]
Can you also add a small test (or feel free to put that inside `MultisigWallet`) for the `0 lines between state variable declarations` rule just to make sure that noone will undeliberately break it in future.

**Comment by moodysalem** [comment]
@SerCeMan I fixed the tests. 

> `.betweenInside(STATEMENT, ELSE, IF_STATEMENT).spaces(1)`

I'll try to fix the `else` line break in the next PR. But how do I fix the problem where the cursor indentation is incorrect when starting a new line within a struct, prior to autoformatting?

image

**Comment by moodysalem** [comment]
Also what's your release schedule? It seems like the struct indentation is wrong in the release version 2.0.2, which is quite annoying since you basically can't autoformat in files with structs.

**Comment by SerCeMan** [comment]
> But how do I fix the problem where the cursor indentation is incorrect when starting a new line within a struct, prior to autoformatting?

`me.serce.solidity.ide.formatting.SolFormattingBlock#newChildIndent` is responsible for that. I might miss indent calculations for structs.

> Also what's your release schedule

I haven't had a chance to work much on the project recently, so there has not been that many features to release. Although, it seems like there is a good bunch of features now, so I'll publish the new version this weekend :)

**Comment by SerCeMan** [comment]
Hi, @moodysalem!

I want to publish the new version today or tomorrow. But if you're going to submit more PRs, I'll be happy to wait for them. What do you think?

**Comment by moodysalem** [comment]
How much work is it for you to publish a new version? I'd like to use what's available ASAP, but probably don't have much time to work on this again until Thursday or later. If you can do something like [semantic-release](https://github.com/semantic-release/semantic-release) with travis, that'd be great so these updates can be available more frequently.

**Comment by SerCeMan** [comment]
@moodysalem No worries, I've already pushed the new version. It's not a problem to release IJ plugins often, but it might be quite annoying for people to update them all the time.

**Comment by SerCeMan** [comment]
BTW, I applied a quick fix so that it doesn't move `else` onto the next line. But currently, there is still no way of enforcing it being on the same line

**Pull request merged**
