### PR TITLE
feature: validate function calls

### PR DESCRIPTION
**Pull request by mbolotov**

### CODE REVIEW

**Review by SerCeMan — COMMENTED** [review]
Thanks! I'm happy to accept the PR, however, just to check, are you planning on introducing more similar inspections or is it a largely one-of? If more, then I wonder if it's worth going down the path of integrating with LSP for similar compile-error-type checks. What do you think?

**Comment by mbolotov** [comment]
I have never been using LSP so far. Could you briefly describe how do you see the integration with LSP in our case?

**Review by SerCeMan — APPROVED** [review]
Reimplementing all of the inspections that produce compiler-related warnings is a large effort and it's unlikely to be ever complete as language versions evolve, especially if the goal is supporting multiple compilers at the same time.  Maybe LSP isn't the best solution but rather some way to obtain compiler output for the majority of build systems, as the alternative is reimplementing the compiler N times.

**Comment by SerCeMan** [comment]
It seems that we could re-use something along the lines of: 
https://blog.jetbrains.com/platform/2023/07/lsp-for-plugin-developers/

**Comment by mbolotov** [comment]
it's really looks promising. 
however, I haven't found a good Solidity LSP implementation yet. Do you know any? 
https://github.com/qiuxiang/solidity-ls seems has a limited set of capabilities and is not developing actively.

**Comment by mbolotov** [comment]
Oh, you are right. It's strange that google did not show me this at the first line.

**Pull request merged**
